language: node_js

node_js:
  - "6"
  - "8"
  - "10"
env:
  - SERVERLESS_VERSION=latest
  - SERVERLESS_VERSION=latest~1
  - SERVERLESS_VERSION=latest~2
  - SERVERLESS_VERSION=latest~3
  - SERVERLESS_VERSION=latest~4

before_install:
  - npm i -g npm@6

install:
  - travis_retry npm install
  - npm install --no-save --ignore-scripts `npx npm-get-version serverless@$SERVERLESS_VERSION`

sudo: false

after_success: npm run coverage
